[package]
name = "culling_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
wide = { version = "0.7", optional = true }

[features]
default = []
simd = ["wide"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
