# Default configuration for gatotkacas
# MiniMessage format is used for all messages
messages:
  usage: "<gray>/gatotkacas <yellow>[reload|info|diag]</yellow></gray>"
  no-permission: "<red>No permission.</red>"
  reloaded: "<green>Configuration reloaded.</green>"
  info: "<gray>Running <green>gatotkacas</green> v<version></gray> | <gray>tick:<green><culled></green>/<green><processed></green> (<green><ratio></green>)</gray> | <gray>window:<green><wculled></green>/<green><wprocessed></green> (<green><wratio></green>)</gray>"

features:
  bstats:
    enabled: true
    # Get a service id at https://bstats.org/ for your plugin
    service-id: 0
  native:
    enabled: true
    # kosongkan untuk auto-pick sesuai OS di plugins/gatotkacas/natives/<nama>
    # atau isi path relatif terhadap folder plugin (plugins/gatotkacas/)
    # Contoh Linux yang benar (relatif): "natives/libculling_rs.so"
    library: ""
    auto-download:
      enabled: true
      url: "https://github.com/RanggaGibran/gatotkacas/releases/download/v0.1.1/culling_rs-linux-x86_64.so"
      sha256: "9f03e31260e94fe2c0551009fe0bfe91651c7eb82881082cd2d620921a6c931f"
      # Optional per-OS URLs (picked automatically when url is empty)
      per-os:
        windows:
          url: ""
          sha256: ""
        linux:
          url: ""
          sha256: ""
        macos:
          url: ""
          sha256: ""
  culling:
    enabled: true
    max-distance: 48.0
    speed-threshold: 0.05
    cos-angle-threshold: 0.25
    interval-ticks: 20
    max-entities-per-tick: 512
    compute-timeout-ms: 75
    use-direct-buffers: true
    metrics: true
    frustum-approx: false
    whitelist: []
    blacklist: ["PLAYER", "ARMOR_STAND", "ITEM_FRAME"]
    ratio-percent: true
    alarm-enabled: false
    alarm-threshold: 0.50
    alarm-cooldown-seconds: 30
    window-seconds: 60
    worlds-include: []
    worlds-exclude: []
    chunk-radius: 0
  # Optional per-entity-type thresholds overriding global values
  # Example:
  # type-thresholds:
  #   ZOMBIE:
  #     max-distance: 40.0
  #     speed-threshold: 0.05
  #     cos-angle-threshold: 0.25
  type-thresholds: {}

  # Cancel spawn packets for culled entities (requires ProtocolLib on server)
  packet-culling:
    enabled: false
    exclude-types: ["PLAYER", "ARMOR_STAND"]

  # Visual item stack holograms with countdown auto-clear
  item-stacks:
    enabled: true
    # Group radius in blocks for similar items
    radius: 3.0
    # Seconds before auto-clear once no new items join the stack
    lifetime-seconds: 60
    # How often to update holograms (ticks)
    update-period-ticks: 5
    # Minimum total count before showing a hologram
    min-count-to-show: 5
    # Pull nearby similar items toward the stack leader to merge faster
    pull-enabled: true
    # Velocity impulse magnitude applied per tick toward leader (blocks/tick)
    pull-strength: 0.22
    # If within this distance to leader, snap-teleport to leader to force merge
    pull-teleport-distance: 0.35

  # Adapt view/simulation distance based on MSPT
  adaptive-distance:
    enabled: true
    high-mspt: 45.0
    low-mspt: 30.0
    min-view-distance: 6
    max-view-distance: 10
    min-sim-distance: 4
    max-sim-distance: 8
    period-ticks: 200

  # Redstone guard to reduce clock spam
  redstone-guard:
    enabled: true
    window-ticks: 200
    toggle-limit: 500

  # Skip creature spawns when no nearby players
  spawn-throttle:
    enabled: true
    player-radius: 48.0
    reasons: ["NATURAL", "SPAWNER"]
    ai:
      enabled: true
      radius: 80.0
      period-ticks: 40
      max-per-tick: 200

# Small server-side tweaks
tweaks:
  enabled: true
  hopper:
    throttle-enabled: true
    interval-ticks: 8
  item:
    aggressive-merge-enabled: true
    merge-radius: 1.5
    max-merge-per-tick: 128
  # Optional per-world tracking range hints (blocks); 0 to ignore
  tracking-range-per-world: {}

monitor:
  window-ticks: 1200
  report:
    enabled: false
    period-seconds: 15
    path: reports/status.json
