# Default configuration for gatotkacas
# MiniMessage format is used for all messages
messages:
  usage: "<gray>/gatotkacas <yellow>[reload|info|diag]</yellow></gray>"
  no-permission: "<red>No permission.</red>"
  reloaded: "<green>Configuration reloaded.</green>"
  info: "<gray>Running <green>gatotkacas</green> v<version></gray> | <gray>tick:<green><culled></green>/<green><processed></green> (<green><ratio></green>)</gray> | <gray>window:<green><wculled></green>/<green><wprocessed></green> (<green><wratio></green>)</gray>"

features:
  bstats:
    enabled: true
    # Get a service id at https://bstats.org/ for your plugin
    service-id: 0
  native:
    enabled: true
    # kosongkan untuk auto-pick sesuai OS di plugins/gatotkacas/natives/<nama>
    # atau isi path relatif terhadap folder plugin (plugins/gatotkacas/)
    # Contoh Linux yang benar (relatif): "natives/libculling_rs.so"
    library: ""
    auto-download:
      enabled: true
      url: "https://github.com/RanggaGibran/gatotkacas/releases/download/v0.1.2/culling_rs-linux-x86_64.so"
      sha256: "4b5dcd6ebff55cc15beac587e7ccbd8d0b421ca7064c4b4785423945b848f858"
      # Optional per-OS URLs (picked automatically when url is empty)
      per-os:
        windows:
          url: ""
          sha256: ""
        linux:
          url: ""
          sha256: ""
        macos:
          url: ""
          sha256: ""
  culling:
    enabled: true
    max-distance: 48.0
    speed-threshold: 0.05
    cos-angle-threshold: 0.25
    interval-ticks: 20
    max-entities-per-tick: 512
    compute-timeout-ms: 75
    use-direct-buffers: true
    metrics: true
    frustum-approx: false
    whitelist: []
    blacklist: ["PLAYER", "ARMOR_STAND", "ITEM_FRAME"]
    ratio-percent: true
    alarm-enabled: false
    alarm-threshold: 0.50
    alarm-cooldown-seconds: 30
    window-seconds: 60
    worlds-include: []
    worlds-exclude: []
    chunk-radius: 0
  # Optional per-entity-type thresholds overriding global values
  # Example:
  # type-thresholds:
  #   ZOMBIE:
  #     max-distance: 40.0
  #     speed-threshold: 0.05
  #     cos-angle-threshold: 0.25
  type-thresholds: {}
  # Entities that should never be culled; always visible to all players
  protected-types:
    - VILLAGER
    - ZOMBIE_VILLAGER
    - WANDERING_TRADER
    - BOAT
    - CHEST_BOAT
    - MINECART
    - CHEST_MINECART
    - HOPPER_MINECART
    - FURNACE_MINECART
    - TNT_MINECART
    - COMMAND_BLOCK_MINECART
    - SPAWNER_MINECART

  # Cancel spawn packets for culled entities (requires ProtocolLib on server)
  packet-culling:
    enabled: true
    budget:
      enabled: true
      max-spawns-per-tick: 20     # per-player spawn packets allowed each tick
      always-send-within: 12.0    # always allow if within this distance to player
      queue-cap: 256              # per-player queued spawn packets cap; drop farthest when full
      queue-ttl-ticks: 100        # drop queued packets older than this
      dynamic:
        enabled: true             # auto-adjust per-player cap based on MSPT
        fast-mspt: 32.0           # if avg MSPT <= fast-mspt use fast-per-tick
        fast-per-tick: 40         # generous cap when server is healthy
        slow-mspt: 48.0           # if avg MSPT >= slow-mspt use slow-per-tick
        slow-per-tick: 12         # tighter cap when server is lagging
        smoothing-ticks: 10       # ticks for exponential smoothing between targets

  # Client-side particle limiter via GUI (/plimit)
  particle-limit:
    enabled: true
    exclude-types: ["PLAYER", "ARMOR_STAND"]

  # Visual item stack holograms with countdown auto-clear
  item-stacks:
    enabled: true
    # Group radius in blocks for similar items
    radius: 3.0
    # Seconds before auto-clear once no new items join the stack
    lifetime-seconds: 60
    # How often to update holograms (ticks)
    update-period-ticks: 5
    # Minimum total count before showing a hologram
    min-count-to-show: 5
    # Pull nearby similar items toward the stack leader to merge faster
    pull-enabled: true
    # Velocity impulse magnitude applied per tick toward leader (blocks/tick)
    pull-strength: 0.22
    # If within this distance to leader, snap-teleport to leader to force merge
    pull-teleport-distance: 0.35
    # Hologram readability options
    holo-full-bright: true
    holo-background-alpha: 170
    holo-line-width: 180

  # Adapt view/simulation distance based on MSPT
  adaptive-distance:
    enabled: true
    high-mspt: 45.0
    low-mspt: 30.0
    min-view-distance: 6
    max-view-distance: 10
    min-sim-distance: 4
    max-sim-distance: 8
    period-ticks: 200

  # Redstone guard to reduce clock spam
  redstone-guard:
    enabled: true
    window-ticks: 200
    toggle-limit: 500
    # When a chunk exceeds the limit, we back off redstone for a cooldown with exponential backoff,
    # but still allow 1 in N pulses to pass so farms can progress slowly without lag spikes.
    cooldown-initial-ticks: 100
    cooldown-max-ticks: 1200
    backoff-multiplier: 2.0
    duty-pass-every: 5
    notification:
      enabled: true
      # how long the hologram stays (seconds)
      ttl-seconds: 300
      # per-chunk cooldown before showing another hologram (seconds)
      cooldown-seconds: 120
    # visual tweaks for readability
    full-bright: true           # force max brightness so text is bright at night/shade
    background-alpha: 190       # 0-255 alpha for dark background rectangle
    line-width: 240             # pixels before wrapping; higher = fewer wraps
    # safety limits
    max-active: 64              # global cap of active redstone holograms
    replace-oldest-when-full: false  # if true, evict the oldest when at cap; otherwise skip
    min-update-interval-ticks: 20    # rate-limit text refresh when spammed by the same chunk

  # Skip creature spawns when no nearby players
  spawn-throttle:
    enabled: true
    player-radius: 48.0
    reasons: ["NATURAL", "SPAWNER"]
    ai:
      enabled: true
      radius: 80.0
      period-ticks: 40
      max-per-tick: 200

  # XP orb + Projectile sweeper (merge/cap per chunk, orphan-despawn)
  sweeper:
    enabled: true
    period-ticks: 40            # how often to run
    player-radius: 64.0         # orbs/projectiles farther than this from any player are orphans
    min-age-ticks: 60           # don't touch very fresh entities
    xp:
      merge-radius: 2.5         # merge orbs within this radius
      max-per-chunk: 64         # hard cap per chunk after merging
      max-merge-per-tick: 128   # safety processing cap per run
    projectile:
      types: ["ARROW", "TRIDENT", "SNOWBALL"]
      merge-radius: 2.0         # collapse tight clusters; keep one, remove others
      max-per-chunk: 96         # hard cap per chunk
      max-remove-per-tick: 128  # safety processing cap per run

  # Hopper microscheduler (token bucket per grid)
  hopper-microscheduler:
    enabled: true
    grid-size-chunks: 2           # cell size in chunks (2x2 chunks)
    base-credits-per-tick: 2      # base tokens per cell per tick
    near-player-bonus: 3          # extra tokens for cells near players
    player-radius: 64.0           # radius to consider player proximity
    coalesce-window-ticks: 5      # suppress repeated src->dst moves within this window
    max-burst: 8                  # cap stored tokens per cell
    stall-bypass-attempts: 3      # allow hopper after this many consecutive stalls even if out of tokens
    max-debt: 8                   # how far a cell can dip into negative tokens when bypassing stalls

# Small server-side tweaks
tweaks:
  enabled: true
  hopper:
    throttle-enabled: false      # legacy simple throttle; auto-disabled when hopper-microscheduler is enabled
    interval-ticks: 8
  item:
    aggressive-merge-enabled: true
    merge-radius: 1.5
    max-merge-per-tick: 128
  # Optional per-world tracking range hints (blocks); 0 to ignore
  tracking-range-per-world: {}

monitor:
  window-ticks: 1200
  report:
    enabled: false
    period-seconds: 15
    path: reports/status.json
