name: gatotkacas
main: id.rnggagib.Plugin
version: 0.1.2
api-version: '1.21'

commands:
  plimit:
    description: Open particle limit GUI
    usage: /plimit
    permission: gatotkacas.plimit

permissions:
  gatotkacas.plimit:
    default: true
    description: Allow player to set own particle limit
