name: Build Native (culling-rs)

on:
  push:
    paths:
      - 'native/culling-rs/**'
      - '.github/workflows/native-build.yml'
  pull_request:
    paths:
      - 'native/culling-rs/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build culling-rs
        working-directory: native/culling-rs
        run: cargo build --release
      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp native/culling-rs/target/release/*.dll artifacts/
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp native/culling-rs/target/release/*.dylib artifacts/
          else
            cp native/culling-rs/target/release/*.so artifacts/
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: culling-rs-${{ matrix.os }}
          path: artifacts/*